---
- name: "Update Kubernetes Cluster"
  hosts: localhost
  gather_facts: false

  vars:
    cluster_name: "rag-app-cluster"
  
  tasks:
  - name: "Connect to cluster (update kubeconfig)"
    shell: "gcloud container clusters get-credentials {{ cluster_name }} --zone {{ gcp_zone }} --project {{ gcp_project }}"
  
  - name: "Copy docker tag file"
    copy:
      src: .docker-tag
      dest: .docker-tag
      mode: 0644

  - name: "Get docker tag"
    shell: "cat .docker-tag"
    register: tag

  - name: "Print tag"
    debug:
      var: tag
  
  - name: "Update Deployment for Frontend"
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Deployment
        metadata:
          name: frontend
          namespace: "{{cluster_name}}-namespace"
        spec:
          selector:
            matchLabels:
              run: frontend
          template:
            metadata:
              labels:
                run: frontend
            spec:
              containers:
              - image: "gcr.io/{{ gcp_project }}/rag-detective-app-frontend:{{ tag.stdout}}"
                imagePullPolicy: Always
                name: frontend
                ports:
                - containerPort: 80
                  protocol: TCP
              restartPolicy: Always
  
  - name: "Update Deployment for API Service"
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Deployment
        metadata:
          name: api
          namespace: "{{cluster_name}}-namespace"
        spec:
          selector:
            matchLabels:
              run: api
          template:
            metadata:
              labels:
                run: api
            spec:
              volumes:
                - name: persistent-vol
                  emptyDir: {}
                - name: google-cloud-key
                  secret:
                    secretName: gcp-service-key
              containers:
              - image: gcr.io/{{ gcp_project }}/rag-detective-app-api-service:{{ tag.stdout}}
                imagePullPolicy: Always
                name: api
              restartPolicy: Always